from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class RichManAssets: 


	# Click Rule Assets
	#  
	C_RM_ROB_CHOICE_1 = RuleClick(roi_front=(155,436,100,100), roi_back=(155,436,100,100), name="rm_rob_choice_1")
	#  
	C_RM_ROB_CHOICE_2 = RuleClick(roi_front=(430,527,100,100), roi_back=(430,527,100,100), name="rm_rob_choice_2")
	#  
	C_RM_ROB_CHOICE_3 = RuleClick(roi_front=(727,526,100,100), roi_back=(727,526,100,100), name="rm_rob_choice_3")
	#  
	C_RM_ROB_CHOICE_4 = RuleClick(roi_front=(1015,369,100,100), roi_back=(1015,369,100,100), name="rm_rob_choice_4")
	#  
	C_RM_FIGHT_BOSS_ENTER = RuleClick(roi_front=(561,347,49,73), roi_back=(561,347,49,73), name="rm_fight_boss_enter")
	#  
	C_RM_RANDOM_CLOSE_SAFE = RuleClick(roi_front=(479,513,326,144), roi_back=(479,513,326,144), name="rm_random_close_safe")
	#  
	C_RM_RANDOM_CLOSE_SAFE_MAIN = RuleClick(roi_front=(1102,208,153,327), roi_back=(1102,208,153,327), name="rm_random_close_safe_main")


	# Image Rule Assets
	# 投掷骰子 
	I_RM_THROW = RuleImage(roi_front=(1139,604,70,43), roi_back=(1084,523,183,196), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_rm_throw.png")
	# 大富翁主界面已锁定阵容
	I_RM_MAIN_LOCK = RuleImage(roi_front=(886,646,31,30), roi_back=(871,620,69,76), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_lock.png")
	# 大富翁主界面未锁定阵容
	I_RM_MAIN_UNLOCK = RuleImage(roi_front=(886,646,31,30), roi_back=(871,620,69,76), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_unlock.png")
	#  
	I_RM_MODE_ROB = RuleImage(roi_front=(486,28,306,32), roi_back=(465,16,349,54), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_rob.png")
	# 投掷对决模式标志 
	I_RM_MODE_THROW = RuleImage(roi_front=(532,312,215,130), roi_back=(490,233,320,264), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_throw.png")
	#  
	I_RM_FIGHT_UNLOCK = RuleImage(roi_front=(1132,510,32,32), roi_back=(1121,499,53,51), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_unlock.png")
	#  
	I_RM_FITGHT_ANCHOR = RuleImage(roi_front=(555,433,50,28), roi_back=(163,100,1011,473), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fitght_anchor.png")
	#  
	I_RM_MODE_FIGHT = RuleImage(roi_front=(1137,604,83,38), roi_back=(1117,585,121,76), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_fight.png")
	#  
	I_RM_FIGHT_LOCK = RuleImage(roi_front=(1132,511,32,32), roi_back=(1121,502,53,51), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_lock.png")
	#  
	I_RM_FIGHT_GOTO_RECORDS = RuleImage(roi_front=(1028,639,41,34), roi_back=(1015,619,69,66), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_goto_records.png")
	#  
	I_RM_FIGHT_BOSS_GOTO_RECORDS = RuleImage(roi_front=(1021,642,41,34), roi_back=(1005,626,69,66), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_boss_goto_records.png")
	#  
	I_RM_MODE_FIGHT_BOSS = RuleImage(roi_front=(1135,601,83,38), roi_back=(1117,585,121,76), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_mode_fight_boss.png")
	#  
	I_RM_FIGHT_LOCK_BOSS = RuleImage(roi_front=(1129,515,32,32), roi_back=(1118,502,53,51), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_lock_boss.png")
	#  
	I_RM_FIGHT_UNLOCK_BOSS = RuleImage(roi_front=(1129,515,32,32), roi_back=(1118,502,53,51), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_fight_unlock_boss.png")
	# 投掷按钮 
	I_RM_THROW_FIGHT = RuleImage(roi_front=(1053,582,83,38), roi_back=(1034,562,121,76), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_rm_throw_fight.png")
	#  
	I_LEVEL_UP = RuleImage(roi_front=(530,117,225,42), roi_back=(494,84,297,104), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_level_up.png")
	#  
	I_CINQUE_NOT_ENOUGH = RuleImage(roi_front=(356,123,90,51), roi_back=(336,82,129,106), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_cinque_not_enough.png")


	# Ocr Rule Assets
	# 骰子数量 
	O_CINQUE_COUNT = RuleOcr(roi=(1146,670,58,33), area=(1146,670,58,33), mode="Digit", method="Default", keyword="", name="cinque_count")
	#  
	O_LEVEL_EXPERIENCE = RuleOcr(roi=(939,17,106,39), area=(934,12,116,49), mode="DigitCounter", method="Default", keyword="", name="level_experience")
	#  
	O_LEVEL = RuleOcr(roi=(1099,19,64,35), area=(1099,19,64,35), mode="DigitCounter", method="Default", keyword="", name="level")


	# Image Rule Assets
	# 庭院进入活动 
	I_MAIN_GOTO_ACT = RuleImage(roi_front=(1188,228,35,28), roi_back=(1164,134,83,393), threshold=0.7, method="Template matching", file="./tasks/RichMan/rm/as_main_goto_act.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_skip_button.png")
	# 进入主要的战斗界面 
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(1064,178,39,139), roi_back=(991,88,155,370), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/as_to_battle_main.png")
	#  
	I_CHECK_RM_MAIN = RuleImage(roi_front=(148,13,174,47), roi_back=(121,0,227,72), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_check_rm_main.png")
	#  
	I_CHECK_RM_RICHMAN = RuleImage(roi_front=(148,13,140,47), roi_back=(121,0,227,72), threshold=0.8, method="Template matching", file="./tasks/RichMan/rm/rm_check_rm_richman.png")
