from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DuelAssets: 


	# Click Rule Assets
	# 战斗数据 
	C_D_BATTLE_DATA = RuleClick(roi_front=(584,279,100,100), roi_back=(584,279,100,100), name="d_battle_data")
	# 点击第五手上式神位置，获得式神名称 
	C_DUEL_CLICK_5 = RuleClick(roi_front=(105,23,52,47), roi_back=(105,23,52,47), name="duel_click_5")
	#  
	C_DUEL_CLICK_4 = RuleClick(roi_front=(178,23,52,47), roi_back=(178,23,52,47), name="duel_click_4")
	#  
	C_DUEL_CLICK_3 = RuleClick(roi_front=(251,23,52,47), roi_back=(251,23,52,47), name="duel_click_3")
	#  
	C_DUEL_CLICK_2 = RuleClick(roi_front=(324,23,52,47), roi_back=(324,23,52,47), name="duel_click_2")
	#  
	C_DUEL_CLICK_1 = RuleClick(roi_front=(397,23,52,47), roi_back=(397,23,52,47), name="duel_click_1")
	#  
	C_SELECT_BAN = RuleClick(roi_front=(747,258,123,121), roi_back=(747,258,123,121), name="select_ban")


	# Image Rule Assets
	# 点击阵容 
	I_D_TEAM = RuleImage(roi_front=(813,288,34,74), roi_back=(785,259,115,119), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team.png")
	# 一键切换所有的御魂 
	I_D_TEAM_SWTICH = RuleImage(roi_front=(1082,85,38,41), roi_back=(1082,85,38,41), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_team_swtich.png")
	# description 
	I_D_BATTLE = RuleImage(roi_front=(1153,573,100,100), roi_back=(1123,537,154,177), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle.png")
	# 战斗带保护的 
	I_D_BATTLE_PROTECT = RuleImage(roi_front=(1153,578,100,100), roi_back=(1118,553,155,149), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle_protect.png")
	# 自动上阵 
	I_D_AUTO_ENTRY = RuleImage(roi_front=(23,118,53,54), roi_back=(2,97,93,96), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_auto_entry.png")
	# 主界面的感叹号 
	I_D_HELP = RuleImage(roi_front=(783,500,29,30), roi_back=(778,476,49,78), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_help.png")
	# 准备 
	I_D_PREPARE = RuleImage(roi_front=(1127,541,100,100), roi_back=(1127,541,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_prepare.png")
	# 胜利 
	I_D_VICTORY = RuleImage(roi_front=(433,76,100,100), roi_back=(433,76,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_victory.png")
	# 失败 
	I_D_FAIL = RuleImage(roi_front=(422,66,100,100), roi_back=(422,66,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_fail.png")
	# 战 
	I_D_WORD_BATTLE = RuleImage(roi_front=(613,41,54,54), roi_back=(600,24,84,85), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_word_battle.png")
	# 名士的星星 
	I_D_CELEB_STAR = RuleImage(roi_front=(646,450,33,37), roi_back=(551,433,185,67), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_star.png")
	# 名士专属 
	I_D_CELEB_HONOR = RuleImage(roi_front=(338,641,25,30), roi_back=(199,606,222,76), threshold=0.75, method="Template matching", file="./tasks/Duel/duel/duel_d_celeb_honor.png")
	# 练 
	I_BATTLE_WITH_TRAIN = RuleImage(roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_with_train.png")
	# 练2 
	I_BATTLE_WITH_TRAIN2 = RuleImage(roi_front=(1161,588,78,81), roi_back=(1114,547,163,172), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_with_train2.png")
	# 斗技模式（普通） 
	I_BATTLE_TYPE_COMMON = RuleImage(roi_front=(439,278,90,88), roi_back=(439,278,90,88), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_battle_type_common.png")
	# 活动的战斗按钮 
	I_D_BATTLE2 = RuleImage(roi_front=(1171,592,69,78), roi_back=(1119,566,154,143), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_battle2.png")
	# 禁用 
	I_BAN = RuleImage(roi_front=(1139,565,77,72), roi_back=(1122,545,114,116), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_ban.png")
	# 左上角的退出 
	I_DUEL_EXIT = RuleImage(roi_front=(14,12,43,41), roi_back=(14,12,43,41), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_exit.png")
	# ban选界面 
	I_D_CHECK_BAN = RuleImage(roi_front=(611,36,56,62), roi_back=(590,14,100,100), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_d_check_ban.png")
	# 斗技荣誉图标 
	I_DUEL_HONOR = RuleImage(roi_front=(186,633,20,20), roi_back=(175,631,242,47), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_honor.png")
	# 胜利分享 
	I_D_WIN_SHARE = RuleImage(roi_front=(1123,608,82,73), roi_back=(1123,608,82,73), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/d_win_share.png")
	#  
	I_BAN_ENSURE = RuleImage(roi_front=(1123,578,111,46), roi_back=(1123,578,111,46), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_ban_ensure.png")
	#  
	I_DUEL_CELEB_HONOR = RuleImage(roi_front=(297,633,20,20), roi_back=(172,632,249,26), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_celeb_honor.png")
	# 斗技入口附属消息页
	I_DUEL_MAIN_UESLESS_MESSAGE = RuleImage(roi_front=(526,224,222,56), roi_back=(521,219,232,66), threshold=0.8, method="Template matching", file="./tasks/Duel/duel/duel_duel_main_uesless_message.png")


	# Ocr Rule Assets
	# 荣誉 
	O_D_HONOR = RuleOcr(roi=(233,643,131,31), area=(233,643,131,31), mode="DigitCounter", method="Default", keyword="", name="d_honor")
	# 分数 
	O_D_SCORE = RuleOcr(roi=(604,484,108,28), area=(604,484,108,28), mode="DigitCounter", method="Default", keyword="", name="d_score")
	# 式神名称5 
	O_D_NAME_5 = RuleOcr(roi=(78,97,113,32), area=(78,97,113,32), mode="Single", method="Default", keyword="", name="d_name_5")
	# 式神名称4 
	O_D_NAME_4 = RuleOcr(roi=(148,97,112,25), area=(148,97,112,25), mode="Single", method="Default", keyword="", name="d_name_4")
	# 式神名称3 
	O_D_NAME_3 = RuleOcr(roi=(220,97,112,25), area=(220,97,112,25), mode="Single", method="Default", keyword="", name="d_name_3")
	# 式神名称2 
	O_D_NAME_2 = RuleOcr(roi=(292,97,112,25), area=(292,97,112,25), mode="Single", method="Default", keyword="", name="d_name_2")
	# 式神名称1 
	O_D_NAME_1 = RuleOcr(roi=(364,97,112,25), area=(364,97,112,25), mode="Single", method="Default", keyword="", name="d_name_1")
	#  
	O_D_CELEB_HONOR = RuleOcr(roi=(173,633,227,20), area=(173,633,227,20), mode="DigitCounter", method="Default", keyword="", name="d_celeb_honor")
	#  
	O_D_CELEB = RuleOcr(roi=(503,442,250,54), area=(503,442,250,54), mode="Single", method="Default", keyword="", name="d_celeb")

